---
- name: Create the new vnet
  hosts: localhost
  azure_rm_virtualnetwork:
    name: test_vnet01
    resource_group: test
  register: vnet_info
  
- name: Print VNet info
  hosts: localhost
  debug:
   var: vnet_info


