---
- name: Init
  hosts: localhost
  
- name: Create the new vnet  
  azure_rm_virtualnetwork:
    resource_group: test
    name: test_vnet01
  register: vnet_info
  
- name: Print VNet info
  debug:
   var: vnet_info


